# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.token_authenticator:
        class: IEEE\UserBundle\Security\TokenAuthenticator
        
    jwt_token_authenticator:
        class: IEEE\UserBundle\Security\JwtTokenAuthenticator
        autowire: true

    app.post_voter:
        class: IEEE\UserBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false        